package main

var teams = []string{
	"AG2R",
	"Citroën",
	"Astana",
	"Qazaqstan",
	"Bahrain",
	"Victorious",
	"BORA",
	"hansgrohe",
	"Cofidis",
	"EF",
	"Education",
	"EasyPost",
	"Groupama FDJ",
	"INEOS",
	"Grenadiers",
	"Intermarché",
	"Wanty",
	"Gobert",
	"Matériaux",
	"Israel",
	"Premier",
	"Tech",
	"Jumbo",
	"Visma",
	"Lotto",
	"Soudal",
	"Movistar",
	"Quick",
	"Step",
	"Alpha",
	"Vinyl",
	"BikeExchange",
	"Jayco",
	"DSM",
	"Trek",
	"Segafredo",
	"UAE",
	"Emirates",
	"Alpecin",
	"Deceuninck",
	"B&B",
	"Hotels",
	"KTM",
	"CSF",
	"Burgos",
	"BH",
	"Caja Rural",
	"Drone",
	"Hopper",
	"EOLO",
	"Kometa",
	"Equipo",
	"Kern",
	"Pharma",
	"Euskaltel",
	"Euskadi",
	"Human",
	"Powered",
	"Health",
	"Sport",
	"Vlaanderen",
	"Baloise",
	"Arkéa",
	"Samsic",
	"Nordisk",
	"TotalEnergies",
	"Uno-X",
	"Equipo",
	"Felbermayr",
	"Simplon",
	"Wels",
	"Vorarlberg",
	"Tirol",
	"KTM",
	"Union",
	"Raiffeisen",
	"Rad",
	"Tirol",
	"WSA",
	"KTM",
	"Graz",
	"Leomo",
	"Bahrain",
	"Academy",
	"Alpecin",
	"Deceuninck",
	"Bingoal",
	"Minerva",
	"SwiftCarbon",
	"Premier",
	"Tech",
	"China",
	"Glory",
	"Giant",
	"Henan",
	"Lottery",
	"International",
	"Electro",
	"Sparta",
	"Praha",
	"Bornholm",
	"Coloquick",
	"Movistar",
	"Groupama",
	"FDJ",
	"Côte d'Azur",
	"Sauerland",
	"Dauner",
	"Lotto",
	"Kern Haus",
	"Israel",
	"Dynatek",
	"Shimano",
	"Bridgestone",
	"Astana",
	"Qazaqstan",
	"Kuwait",
	"Kaunas",
	"DSM",
	"Jumbo",
	"Visma",
	"Coop",
	"Uno-X",
	"DARE",
	"Tudor",
	"CCN",
	"EF Education",
	"NIPPO",
}

var racePrefixes = []string{
	"Tour",
	"Race",
	"Classic",
	"Tour de",
	"Il",
	"La",
	"Cyclassics",
	"Criterium du",
	"Grand Prix",
	"Giro",
	"Dwars door",
	"Cicliste de",
}

var raceSuffixes = []string{
	"Tour",
	"Classic",
	"Cyclassics",
	"Criterium",
	"Grand Prix",
	"Giro",
}

// TODO Proper tokenizing
var raceNames = []string{
	"Santos Down Under",
	"Cadel Evans",
	"Great Ocean Road",
	"UAE",
	"Omloop",
	"Het Nieuwsblad",
	"Strade Bianche",
	"Paris",
	"Nice",
	"Tirreno",
	"Adriatico",
	"Milano",
	"Sanremo",
	"Volta",
	"Ciclista ",
	"a Catalunya",
	"Minerva",
	"Brugge",
	"De Panne",
	"E3 Saxo Bank",
	"Gent",
	"Wevelgem",
	"Vlaanderen",
	"Ronde van",
	"Itzulia Basque Country",
	"Amstel Gold Race",
	"Paris",
	"Roubaix",
	"Flèche",
	"Wallonne",
	"Liège",
	"Bastogne",
	"Liège",
	"Romandie",
	"Eschborn",
	"Frankfurt",
	"d'Italia",
	"Dauphiné",
	"Suisse",
	"France",
	"Donostia San Sebastian Klasikoa",
	"Pologne",
	"Vuelta ciclista a España",
	"BEMER",
	"Bretagne",
	"Ouest-France",
	"Benelux",
	"Québec",
	"Montréal",
	"Lombardia",
	"Maryland",
	"Flanders",
	"Espana",
	"Toscana",
	"World Championship",
	"Deutschland",
	"Alsace",
	"Slovenia",
	"Brabant",
	"Brussels",
	"Camembert",
	"Rund um Köln",
	"Norway",
	"Hellas",
}

var riderNames = []string{
	"Primoz Roglic",
	"Jonas Vingegaard",
	"Remco Evenepoel",
	"Aleksandr Vlasov",
	"Stefan Küng",
	"Adam Yates",
	"Alexander Kristoff",
	"Pello Bilbao",
	"Sergio Higuita",
	"Biniam Girmay",
	"Alejandro Valverde",
	"Jasper Philipsen",
	"Arnaud Démare",
	"Daniel Martinez",
	"Christophe Laporte",
	"Fabio Jakobsen",
	"Julian Alaphilippe",
	"Nairo Quintana",
	"Jai Hindley",
	"Richard Carapaz",
	"Tim Merlier",
	"Geraint Thomas",
	"Hugo Hofstetter",
	"Joao Almeida",
	"Benoît Cosnefroy",
	"Matej Mohoric",
	"Simon Yates",
	"Ethan Hayter",
	"Lorenzo Rota",
	"Jasper Stuyven",
	"Mads Pedersen",
	"David Gaudu",
	"Guillaume Martin",
	"Michael Matthews",
	"Neilson Powless",
	"Jack Haig",
	"Tiesj Benoot",
	"Dylan Teuns",
	"Valentin Madouas",
	"Warren Barguil",
	"Enric Mas",
	"Olav Kooij",
	"Matteo Trentin",
	"Romain Bardet",
	"Juan Ayuso",
	"Ben O'Connor",
	"Carlos Rodriguez",
	"Damiano Caruso",
	"Michael Woods",
	"Quinten Hermans",
	"Mikel Landa",
	"Marc Hirschi",
	"Diego Ulissi",
	"Giacomo Nizzolo",
	"Brandon McNulty",
	"Michael Valgren",
	"Florian Sénéchal",
	"Tom Pidcock",
	"Gino Mäder",
	"Thymen Arensman",
	"Benjamin Thomas",
	"Mark Cavendish",
	"Alessandro Covi",
	"Dylan Groenewegen",
	"Filippo Ganna",
	"Victor Campenaerts",
	"Jesus Herrada",
	"Jan Hirt",
	"Magnus Cort",
	"Alex Aranburu",
	"Louis Meintjes",
	"Fausto Masnada",
	"Ion Izagirre",
	"Tim Wellens",
	"Bauke Mollema",
	"Axel Zingle",
	"Pavel Sivakov",
	"Julien Simon",
	"Vincenzo Nibali",
	"Max Walscheid",
	"Matis Louvel",
	"Nacer Bouhanni",
	"Anthony Turgis",
	"Alberto Dainese",
	"Jakob Fuglsang",
	"Alexey Lutsenko",
	"Magnus Sheffield",
	"Ruben Guerreiro",
	"Samuele Battistella",
	"Kasper Asgreen",
	"Sonny Colbrelli",
	"Simon Clarke",
	"Vincenzo Albanese",
	"Michael Storer",
	"Thibaut Pinot",
	"Gerben Thijssen",
	"Simone Consonni",
	"Rasmus Tiller",
	"Alexander Kamp",
	"Piet Allegaert",
	"Fernando Gaviria",
	"Elia Viviani",
	"Mauro Schmid",
	"Sam Bennett",
	"Simon Geschke",
	"Mathieu Burgaudeau",
	"Phil Bauhaus",
	"Michal Kwiatkowski",
	"Pascal Ackermann",
	"Jhonnatan Narvaez",
	"Natnael Tesfazion",
	"Toms Skujins",
	"Attila Valter",
	"Sepp Kuss",
	"Oliver Naesen",
	"Domenico Pozzovivo",
	"Clément Champoussin",
	"Alexis Vuillermoz",
	"Bob Jungels",
	"Marco Haller",
	"Bram Welten",
	"Loic Vliegen",
	"Felix Großschartner",
	"Pierre Latour",
	"Xandro Meurisse",
	"Nils Politt",
	"Rafal Majka",
	"Hugo Houle",
	"Gianni Vermeersch",
	"Santiago Buitrago",
	"Mauri Vansevenant",
	"Emanuel Buchmann",
	"Andreas Leknessund",
	"Luca Mozzato",
	"Kévin Vauquelin",
	"Patrick Konrad",
	"Koen Bouwman",
	"Peter Sagan",
	"Filippo Baroncini",
	"Lucas Plapp",
	"Milan Menten",
	"Yves Lampaert",
	"Matteo Sobrero",
	"Anatolii Budiak",
	"Jordi Meeus",
	"Caleb Ewan",
	"Ben Turner",
	"James Fouche",
	"Filippo Zana",
	"Esteban Chaves",
	"Bryan Coquard",
	"Lennard Kämna",
	"Carlos Verona",
	"Giulio Ciccone",
	"Philippe Gilbert",
	"Filippo Fiorelli",
	"Andrea Piccolo",
	"Valentin Ferron",
	"Jan Tratnik",
	"Sebastien Reichenbach",
	"Jambaljamats Sainbayar",
	"Andreas Kron",
	"Georg Zimmermann",
	"Tom Devriendt",
	"Franck Bonnamour",
	"Stan Dewulf",
	"Zdenek Stybar",
	"Ben Tulett",
	"Steven Kruijswijk",
	"Adrien Petit",
	"Rohan Dennis",
	"Connor Swift",
	"Jay Vine",
	"Edward Dunbar",
	"Dorian Godon",
	"Jan Polanc",
	"Victor Lafay",
	"Rudy Molard",
	"Wout Poels",
	"Edvald Boasson-Hagen",
	"Cian Uijtdebroeks",
	"Ivan Sosa",
	"Egan Bernal",
	"Rein Taaramäe",
	"Florian Vermeersch",
	"Geoffrey Bouchard",
	"Sebastian Molano",
	"Nikias Arndt",
	"Alessandro Fedeli",
	"Daniel McLay",
	"Niccolo Bonifazio",
	"Tom Sexton",
	"Sam Watson",
	"Timothy Dupont",
	"Emiliano Contreras",
	"Aurélien Paret-Peintre",
	"Anthon Charmig",
	"Davide Formolo",
	"Nariyuki Masuda",
	"Rune Herregodts",
	"Johannes Staune-Mittet",
	"Matteo Jorgenson",
	"Stefan Bissegger",
	"Max Kanter",
	"Lorenzo Fortunato",
	"Fred Wright",
	"Kaden Groves",
	"Sep Vanmarcke",
	"Jenthe Biermans",
	"Stephen Williams",
	"Alberto Bettiol",
	"George Bennett",
	"Edward Theuns",
	"Hugh Carthy",
	"Sam Welsford",
	"Baptiste Planckaert",
	"Harm Vanhoucke",
	"Wilco Kelderman",
	"Tadej Pogacar",
	"Wout van Aert",
	"Arnaud De Lie",
	"Mathieu van der Poel",
	"Dylan van Baarle",
	"Danny van Poppel",
	"Van Avermaet Greg",
	"Dries De Bondt",
	"Kragh Andersen Søren",
	"Juan Pedro Lopez",
	"Taco van der Hoorn",
	"Ángel López Miguel",
	"Alessandro De Marchi",
	"Mick Van Dijke",
	"Richie Porte",
	"Christian Eiking Odd",
	"Tao Geoghegan Hart",
	"Jasper De Buyst",
}

var riderTypes = []string{
	"Sprinter",
	"Bergfahrer",
	"Edelhelfer",
	"Etappenjäger",
	"GC-Fahrer",
	"Zeitfahrer",
}

var feelings = []string{
	"Glücklich",
	"Erschöpft",
	"Traurig",
	"Enttäuscht",
	"Niedergeschlagen",
	"Stolz",
	"Gelangweilt",
}

var teamFunctions = []string{
	"Sportlicher Leiter",
	"Sportlicher Leiter",
	"Physio",
	"Ernährungsberater",
	"Mechaniker",
	"Sportdirektor",
	"Social-Media Berater",
	"Pressesprecher",
	"Manager",
}
