# https://taskfile.dev

version: 3

tasks:
  build:
    cmds:
      - go build -ldflags "-X main.Version=`git describe --tags`"  -v .
    sources:
      - "radsportsalat.go"
      - "data.go"
    generates:
      - "./radsportsalat"

  run:
    deps: [build]
    cmds:
      - ./radsportsalat

  release:
    cmds:
      - git tag
      - read -p "Version v1.1.1 " version ; git tag $version ; docker build -t ghcr.io/noqqe/radsportsalat:$version . ;  docker push ghcr.io/noqqe/radsportsalat:$version
      - git push --tags
    interactive: true

  default:
    cmds:
      - task: build
